include: package:flutter_lints/flutter.yaml

# Optional: Add or override lint rules below
linter:
  rules:
    use_key_in_widget_constructors: true
    library_private_types_in_public_api: false
    # Add other custom lint rules here

